---
include:
- "**/*.rb"
exclude:
- .git/**/*
- .logs/**/*
- spec/**/*
- test/**/*
- vendor/**/*
require: []
domains: []
reporters:
- require_not_found
#- standardrb
#plugins:
  #- solargraph-standardrb
max_files: 5000
