#!/usr/bin/env bash

set -euo pipefail

source "lib/globals.sh"
source "lib/config.sh"
source "lib/util.sh"
source "lib/common.sh"
source "lib/install.sh"
source "lib/uninstall.sh"
source "lib/main.sh"

main "$@"
