name: Run tests
on:
  push:
    branches:
      - master
  #pull_request:
    #branches:
      #- master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Pull git submodules
      run: git submodule update --init
    - name: Run tests
      run: make
